name: rest-docs-api-spec Fork Release

jobs:
  release-build:
    name: Release Build
    runs-on: ubuntu-latest
    env:
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build & Test
        run: ./mvnw clean install

      - name: Deploy to Bintray
        run: ./release.sh